title: Eugenio Calandrini, PhD # your name (or website title) here
logo: "images/WhatsApp Image 2025-03-08 at 19.03.23.jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  ğŸ”¬ Physicist 
  <br>
  ğŸ’» Data Analyst 
  <br>
  R&D Project Manager.
  <br>
  ğŸ’« Astronomer & Astrophotographer.
  <br>
  ğŸ“ PhD in Bionanotechnology from the Italian Institute of Technology, Master's Degree in Solid State Physics from the Sapienza University of Rome.
  <br>
  ğŸ“ Currently based in San Sebastian, Spain, Testing Engineer in Basquevolt Vitoria-Gasteiz.
  <br>
  Previously:
  <br>
  Post Doc, NanoOptics group at CIC NanoGUNE.
  <br>
  Post Doc, Sorbonne UniversitÃ© Paris.
  <br>
  PhD Student, IIT Genova.
  <br>
  Master Student, Sapienza University of Rome.
  <br>
  ğŸ”—
  <a href="https://www.linkedin.com/in/e-calandrini/">View My LinkedIn Profile</a> 
  <br>
  <a href="https://scholar.google.com/citations?hl=en&user=_WTjBSEAAAAJ&view_op=list_works&sortby=pubdate">View My Google Scholar Profile</a>
  <br>
  <a href="https://www.strava.com/athletes/ecalandrini">View My Strava Profile</a>
 
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-ELT6FFE255 # your Google Analytics tracking ID here
